export const movies = [
  {
    id: "27205",
    title: "Inception",
    description:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    coverImage: "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    thumbnailImage: "https://image.tmdb.org/t/p/original/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg",
    genre: ["Action", "Sci-Fi"],
    year: "2010",
    duration: "2h 28m",
    rating: 10,
    director: "Christopher Nolan",
    writers: ["Christopher Nolan"],
    releaseDate: "July 16, 2010",
    budget: "$160 million",
    revenue: "$836.8 million",
    cast: [
      { name: "Leonardo DiCaprio", character: "Cobb" },
      { name: "Joseph Gordon-Levitt", character: "Arthur" },
      { name: "Ellen Page", character: "Ariadne" },
      { name: "Tom Hardy", character: "Eames" },
      { name: "Ken Watanabe", character: "Saito" },
    ],
    reviews: [
      {
        user: "MovieFan123",
        rating: 9,
        comment:
          "Mind-blowing concept and excellent execution. The visuals are stunning and the plot keeps you engaged throughout.",
        date: "2023-05-15",
        likes: 42,
      },
      {
        user: "CinemaLover",
        rating: 8,
        comment: "Great film with an intricate plot. Sometimes it gets a bit confusing but overall a masterpiece.",
        date: "2023-04-22",
        likes: 28,
      },
    ],
  },
  {
    id: "597",
    title: "The Matrix",
    description:
      "A hacker discovers the world is a simulation and joins a rebellion.",
    coverImage: "/placeholder.svg?height=1080&width=1920&text=Shawshank",
    thumbnailImage: "/placeholder.svg?height=450&width=300&text=Shawshank",
    genre: ["Action", "Sci-Fi"],
    year: "1994",
    duration: "2h 22m",
    rating: 8.7,
    director: "Frank Darabont",
    writers: ["Stephen King", "Frank Darabont"],
    releaseDate: "October 14, 1994",
    budget: "$25 million",
    revenue: "$58.3 million",
    cast: [
      { name: "Tim Robbins", character: "Andy Dufresne" },
      { name: "Morgan Freeman", character: "Ellis Boyd 'Red' Redding" },
      { name: "Bob Gunton", character: "Warden Norton" },
    ],
    reviews: [
      {
        user: "ClassicFilmBuff",
        rating: 10,
        comment: "Possibly the best film ever made. A story of hope and perseverance that resonates with everyone.",
        date: "2023-06-10",
        likes: 87,
      },
    ],
  },
  {
    id: "3",
    title: "The Dark Knight",
    description:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    coverImage: "/placeholder.svg?height=1080&width=1920&text=Dark+Knight",
    thumbnailImage: "/placeholder.svg?height=450&width=300&text=Dark+Knight",
    genre: ["Action", "Crime", "Drama"],
    year: "2008",
    duration: "2h 32m",
    rating: 9.0,
    director: "Christopher Nolan",
    writers: ["Jonathan Nolan", "Christopher Nolan"],
    releaseDate: "July 18, 2008",
    budget: "$185 million",
    revenue: "$1.006 billion",
    cast: [
      { name: "Christian Bale", character: "Bruce Wayne / Batman" },
      { name: "Heath Ledger", character: "Joker" },
      { name: "Aaron Eckhart", character: "Harvey Dent" },
      { name: "Michael Caine", character: "Alfred" },
    ],
    reviews: [
      {
        user: "DCFanatic",
        rating: 10,
        comment: "Heath Ledger's performance as the Joker is legendary. One of the best superhero movies ever made.",
        date: "2023-03-18",
        likes: 65,
      },
    ],
  },
  {
    id: "4",
    title: "Pulp Fiction",
    description:
      "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    coverImage: "/placeholder.svg?height=1080&width=1920&text=Pulp+Fiction",
    thumbnailImage: "/placeholder.svg?height=450&width=300&text=Pulp+Fiction",
    genre: ["Crime", "Drama"],
    year: "1994",
    duration: "2h 34m",
    rating: 8.9,
    director: "Quentin Tarantino",
    writers: ["Quentin Tarantino", "Roger Avary"],
    releaseDate: "October 14, 1994",
    budget: "$8 million",
    revenue: "$213.9 million",
    cast: [
      { name: "John Travolta", character: "Vincent Vega" },
      { name: "Samuel L. Jackson", character: "Jules Winnfield" },
      { name: "Uma Thurman", character: "Mia Wallace" },
      { name: "Bruce Willis", character: "Butch Coolidge" },
    ],
    reviews: [
      {
        user: "FilmNoir",
        rating: 9,
        comment: "Tarantino at his best. The non-linear storytelling and dialogue are brilliant.",
        date: "2023-02-05",
        likes: 53,
      },
    ],
  },
  {
    id: "5",
    title: "The Lord of the Rings: The Return of the King",
    description:
      "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    coverImage: "/placeholder.svg?height=1080&width=1920&text=LOTR",
    thumbnailImage: "/placeholder.svg?height=450&width=300&text=LOTR",
    genre: ["Action", "Adventure", "Fantasy"],
    year: "2003",
    duration: "3h 21m",
    rating: 9.0,
    director: "Peter Jackson",
    writers: ["J.R.R. Tolkien", "Fran Walsh", "Philippa Boyens"],
    releaseDate: "December 17, 2003",
    budget: "$94 million",
    revenue: "$1.146 billion",
    cast: [
      { name: "Elijah Wood", character: "Frodo Baggins" },
      { name: "Viggo Mortensen", character: "Aragorn" },
      { name: "Ian McKellen", character: "Gandalf" },
      { name: "Orlando Bloom", character: "Legolas" },
    ],
    reviews: [
      {
        user: "FantasyLover",
        rating: 10,
        comment:
          "A perfect conclusion to an epic trilogy. The battle scenes, the emotional moments, everything is perfect.",
        date: "2023-01-12",
        likes: 78,
      },
    ],
  },
  {
    id: "6",
    title: "Forrest Gump",
    description:
      "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
    coverImage: "/placeholder.svg?height=1080&width=1920&text=Forrest+Gump",
    thumbnailImage: "/placeholder.svg?height=450&width=300&text=Forrest+Gump",
    genre: ["Drama", "Romance"],
    year: "1994",
    duration: "2h 22m",
    rating: 8.8,
    director: "Robert Zemeckis",
    writers: ["Winston Groom", "Eric Roth"],
    releaseDate: "July 6, 1994",
    budget: "$55 million",
    revenue: "$678.2 million",
    cast: [
      { name: "Tom Hanks", character: "Forrest Gump" },
      { name: "Robin Wright", character: "Jenny Curran" },
      { name: "Gary Sinise", character: "Lieutenant Dan Taylor" },
    ],
    reviews: [
      {
        user: "ClassicMovieFan",
        rating: 9,
        comment: "Tom Hanks delivers an unforgettable performance. A beautiful story about life's unpredictability.",
        date: "2023-04-03",
        likes: 61,
      },
    ],
  },
  {
    id: "7",
    title: "The Matrix",
    description:
      "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    coverImage: "/placeholder.svg?height=1080&width=1920&text=The+Matrix",
    thumbnailImage: "/placeholder.svg?height=450&width=300&text=The+Matrix",
    genre: ["Action", "Sci-Fi"],
    year: "1999",
    duration: "2h 16m",
    rating: 8.7,
    director: "Lana Wachowski, Lilly Wachowski",
    writers: ["Lana Wachowski", "Lilly Wachowski"],
    releaseDate: "March 31, 1999",
    budget: "$63 million",
    revenue: "$466.6 million",
    cast: [
      { name: "Keanu Reeves", character: "Neo" },
      { name: "Laurence Fishburne", character: "Morpheus" },
      { name: "Carrie-Anne Moss", character: "Trinity" },
      { name: "Hugo Weaving", character: "Agent Smith" },
    ],
    reviews: [
      {
        user: "SciFiEnthusiast",
        rating: 9,
        comment: "Revolutionary visual effects and a mind-bending concept. Changed action movies forever.",
        date: "2023-05-22",
        likes: 49,
      },
    ],
  },
  {
    id: "8",
    title: "Goodfellas",
    description:
      "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.",
    coverImage: "/placeholder.svg?height=1080&width=1920&text=Goodfellas",
    thumbnailImage: "/placeholder.svg?height=450&width=300&text=Goodfellas",
    genre: ["Biography", "Crime", "Drama"],
    year: "1990",
    duration: "2h 26m",
    rating: 8.7,
    director: "Martin Scorsese",
    writers: ["Nicholas Pileggi", "Martin Scorsese"],
    releaseDate: "September 19, 1990",
    budget: "$25 million",
    revenue: "$47.1 million",
    cast: [
      { name: "Robert De Niro", character: "James Conway" },
      { name: "Ray Liotta", character: "Henry Hill" },
      { name: "Joe Pesci", character: "Tommy DeVito" },
    ],
    reviews: [
      {
        user: "FilmCritic101",
        rating: 10,
        comment:
          "Scorsese's masterpiece. The cinematography, the performances, the soundtrack - everything is perfect.",
        date: "2023-03-30",
        likes: 72,
      },
    ],
  },
  {
    id: "9",
    title: "Interstellar",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    coverImage: "/placeholder.svg?height=1080&width=1920&text=Interstellar",
    thumbnailImage: "/placeholder.svg?height=450&width=300&text=Interstellar",
    genre: ["Adventure", "Drama", "Sci-Fi"],
    year: "2014",
    duration: "2h 49m",
    rating: 8.6,
    director: "Christopher Nolan",
    writers: ["Jonathan Nolan", "Christopher Nolan"],
    releaseDate: "November 7, 2014",
    budget: "$165 million",
    revenue: "$701.8 million",
    cast: [
      { name: "Matthew McConaughey", character: "Cooper" },
      { name: "Anne Hathaway", character: "Brand" },
      { name: "Jessica Chastain", character: "Murph" },
      { name: "Michael Caine", character: "Professor Brand" },
    ],
    reviews: [
      {
        user: "SpaceExplorer",
        rating: 9,
        comment:
          "A visual and emotional masterpiece. The science is fascinating and the father-daughter relationship is heartbreaking.",
        date: "2023-06-18",
        likes: 56,
      },
    ],
  },
  {
    id: "10",
    title: "The Silence of the Lambs",
    description:
      "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
    coverImage: "/placeholder.svg?height=1080&width=1920&text=Silence+of+the+Lambs",
    thumbnailImage: "/placeholder.svg?height=450&width=300&text=Silence+of+the+Lambs",
    genre: ["Crime", "Drama", "Thriller"],
    year: "1991",
    duration: "1h 58m",
    rating: 8.6,
    director: "Jonathan Demme",
    writers: ["Thomas Harris", "Ted Tally"],
    releaseDate: "February 14, 1991",
    budget: "$19 million",
    revenue: "$272.7 million",
    cast: [
      { name: "Jodie Foster", character: "Clarice Starling" },
      { name: "Anthony Hopkins", character: "Dr. Hannibal Lecter" },
      { name: "Scott Glenn", character: "Jack Crawford" },
    ],
    reviews: [
      {
        user: "ThrillerFan",
        rating: 10,
        comment:
          "Hopkins' performance as Hannibal Lecter is one of the greatest in film history. Terrifying and captivating.",
        date: "2023-02-14",
        likes: 68,
      },
    ],
  },
]

export const featuredMovies = movies.filter((movie) => movie.rating > 8.5).slice(0, 5)
